name: CI

on:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt update -y && apt install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
        build-command: "sphinx-build -b html . build"
        docs-folder: "."
