name: CI

on:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # Standard drop-in approach that should work for most people.
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt update -y && apt install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended python3-pip && pip3 install sphinx sphinx_bootstrap_theme"
        build-command: "sphinx-build -b html . _build"
        docs-folder: "source/"
    # Great extra actions to compose with:
    # Create an artifact of the html output.
#     - uses: actions/upload-artifact@v1
#       with:
#         name: DocumentationHTML
#         path: source/docs/_build/html/
    # ===============================
