name: CI

on:
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # Standard drop-in approach that should work for most people.
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt update -y; apt install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended; pip3 install --upgrade pip; pip3 install sphinx; pip3 install sphinx_bootstrap_theme"
        build-command: "make html"
        docs-folder: "source/docs"
    # Great extra actions to compose with:
    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: source/docs/_build/html/
    # ===============================
